### ISSUE TITLE
I got this issue 

### ISSUE THREAD

**Issue by Backtrack89** [plsatin/icingaweb2-module-hardwareinfo#1]
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8mb4', query was: SELECT ho.name1 AS host_name, h.display_name COLLATE latin1_general_ci AS host_display_name, h.icon_image AS host_icon_image, CASE WHEN hs.has_been_checked = 0 OR hs.has_been_checked IS NULL THEN 99 ELSE hs.current_state END AS host_state, hcv_os.varvalue AS os, hcv_cpu.varvalue AS cpu, hcv_ram.varvalue AS ram, hcv_manufacturer.varvalue AS manufacturer, hcv_model.varvalue AS model FROM icinga_objects AS ho
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
LEFT JOIN icinga_customvariablestatus AS hcv_os ON h.host_object_id = hcv_os.object_id AND hcv_os.varname = 'os' COLLATE latin1_general_ci
LEFT JOIN icinga_customvariablestatus AS hcv_cpu ON h.host_object_id = hcv_cpu.object_id AND hcv_cpu.varname = 'cpu' COLLATE latin1_general_ci
LEFT JOIN icinga_customvariablestatus AS hcv_ram ON h.host_object_id = hcv_ram.object_id AND hcv_ram.varname = 'ram' COLLATE latin1_general_ci
LEFT JOIN icinga_customvariablestatus AS hcv_manufacturer ON h.host_object_id = hcv_manufacturer.object_id AND hcv_manufacturer.varname = 'manufacturer' COLLATE latin1_general_ci
LEFT JOIN icinga_customvariablestatus AS hcv_model ON h.host_object_id = hcv_model.object_id AND hcv_model.varname = 'model' COLLATE latin1_general_ci
LEFT JOIN icinga_customvariablestatus AS hcv_os_type ON h.host_object_id = hcv_os_type.object_id AND hcv_os_type.varname = 'os_type' COLLATE latin1_general_ci WHERE (hcv_os_type.varvalue > '') ORDER BY h.display_name COLLATE latin1_general_ci ASC LIMIT 25

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(744): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/share/php/Icinga/Data/Db/DbConnection.php(349): Zend_Db_Adapter_Abstract->fetchRow()
#5 /usr/share/php/Icinga/Data/SimpleQuery.php(584): Icinga\Data\Db\DbConnection->fetchRow()
#6 /usr/share/php/Icinga/Data/SimpleQuery.php(460): Icinga\Data\SimpleQuery->fetchRow()
#7 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(538): Icinga\Data\SimpleQuery->hasResult()
#8 /usr/share/icingaweb2/modules/hardwareinfo/application/views/scripts/index/index.phtml(33): Icinga\Module\Monitoring\DataView\DataView->hasResult()
#9 /usr/share/php/Icinga/Web/View.php(248): include(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#16 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#18 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch()
#19 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#20 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#21 {main}

SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8mb4'

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php(219): PDOStatement->execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#4 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(744): Zend_Db_Adapter_Pdo_Abstract->query()
#5 /usr/share/php/Icinga/Data/Db/DbConnection.php(349): Zend_Db_Adapter_Abstract->fetchRow()
#6 /usr/share/php/Icinga/Data/SimpleQuery.php(584): Icinga\Data\Db\DbConnection->fetchRow()
#7 /usr/share/php/Icinga/Data/SimpleQuery.php(460): Icinga\Data\SimpleQuery->fetchRow()
#8 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(538): Icinga\Data\SimpleQuery->hasResult()
#9 /usr/share/icingaweb2/modules/hardwareinfo/application/views/scripts/index/index.phtml(33): Icinga\Module\Monitoring\DataView\DataView->hasResult()
#10 /usr/share/php/Icinga/Web/View.php(248): include(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#17 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#19 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch()
#20 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#21 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#22 {main}

**Comment by plsatin** [comment]
Edit: /etc/mysql/mysql.conf.d/mysqld.cnf

```conf
character-set-server = latin1
collation-server = latin1_bin

init_connect='SET NAMES latin1'
default_authentication_plugin = mysql_native_password
```

**Comment by plsatin** [comment]
[[Workaround] Database character set broken](https://community.icinga.com/t/workaround-database-character-set-broken/2354)

**Comment by Backtrack89** [comment]
Not usefull.
MyDB runs UTF8 on 

`character-set-server  = utf8                                                                 
collation-server      = utf8_general_ci `

and if i changed it my whole stuff is broken.
Is there a way to Add UTF8 to this addon?

**Comment by plsatin** [comment]
It's not a problem with this module, it's an icingaweb2 problem.  One of the possible solutions:
https://github.com/Icinga/icingaweb2-module-graphite/issues/117
